### ISSUE TITLE
Add how to use with WACAO

### ISSUE THREAD

**Issue by baruchiro** [sidhusmart/WACAO#2]
readme.md Contains only the WhatsApp api

_Sent from my Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sidhusmart** [comment]
Yup - I will be cleaning up the code and documenting steps.

**Comment by sidhusmart** [comment]
I have cleaned up the README file to provide instructions. Let me know if this is helpful and works.
